### ISSUE TITLE
Countdown speed increases

### ISSUE THREAD

**Issue by brijeshPantDaffodil** [pughpugh/react-countdown-clock#16]
I've fed the `seconds` prop with a state variable, and when this variable changes, the clock does show the updated time, **but** the speed with which the time passes *doubles up*!

```
<ReactCountdownClock seconds={this.state.timeRemaining} />
```

The speed further increases as the state variable changes further.

Please fix the issue, or suggest a workaround

**Comment by pughpugh** [comment]
Hi, thanks for reporting the issue.

Yeah that will be because the timer is not cancelled when the props get updated, so you're getting twice as many (or more) tick events. It probably needs a call to `_cancelTimer` at the start of `_setupTimer`.

As a workaround you might be able to call `_cancelTimer` manually via a ref; see http://stackoverflow.com/a/24848228/523866

As for a fix, it will depend when I have time to work on it again. As others have done, you can always create a fork.

Thanks.

**Comment by pughpugh** [comment]
I believe this should have been fixed as part of 3ed3914a949e8b1d60e9026d5bd8efff2e21aa3b . It should be in the next release I cut.

Thanks,
Hugh

**Comment by protoEvangelium** [comment]
@pughpugh  Great app!  Just struggling with the same issue.  Every time I click on an unrelated button on the page, it speeds up the timer.  The clock and the btn are not wired up in any way.

Any status on this?

**Comment by pughpugh** [comment]
Sorry for the delay. I believe this is fixed in `1.1.0`, which I've just deployed to npm.

**Comment by stubbegianni** [comment]
I'm still seeing the same issue. I have this rendered in a material ui tabs component. Every time I change tab it gets faster.

**Comment by pughpugh** [comment]
When I have a moment I'll see if I replicate it.

**Comment by stubbegianni** [comment]
I found the issue:
I calculated the amount of seconds in my render. The problem is every time I changed tabs the amount of seconds got updated. I managed to fix this by calculating the amount of seconds in my constructor and putting it in a state variable.

**Comment by pughpugh** [comment]
I'm glad you found a way around. This does still feel like a bug, as clearly changing the prop causes duplicate timer callbacks to be queued up. But it's not totally clear to me what outcome people would expect if they legitimately changed the seconds; 

* Are they updating the range time being counted down
* Are they updating the current position in the existing countdown
* Are they expecting the timer to reset or continue

**Comment by stubbegianni** [comment]
I was not really updating it on purpose. I was just calculating a 10 min difference between a database date and now. 

At the start this would be 600 seconds, but when changing tabs and going back would recalculate and end up with something smaller than that causing it to bug out.
